### ISSUE TITLE
Dragging on mobile prevents default scroll

### ISSUE THREAD

**Issue by Abisar** [Norserium/react-indiana-drag-scroll#10]
Hi again again 😄. Default swiping on mobile scrolls the whole page vertically, right? So if I have a horizontal `ScrollContainer` in my page and start touch on the container and swipe let's say up, it doesn't work. I also tried `vertical={false}`. Should I use the native browser scroll for mobile?

![asdad](https://user-images.githubusercontent.com/18389149/62420089-2a2c1500-b6a2-11e9-90b3-e4a8b60b668c.gif)
https://qyhqc.csb.app/

**Comment by Norserium** [comment]
I've rewritten the touch processing code in `1.2.0`. It should use native browser scroll for mobile devices now and custom scroll for desktop devices.
