### ISSUE TITLE
onEndScroll fires on any click on the page

### ISSUE THREAD

**Issue by gercog1** [Norserium/react-indiana-drag-scroll#11]
Handler onEndScroll fires on any click on the page :(

**Comment by gercog1** [comment]
ohhh, sorry my bad :) everything works fine in the example

**Comment by Norserium** [comment]
Hello, @gercog1! 

I've added additional checks to the mouse and touch handlers, because there was a probability of incorrect behavior.

Please update to `1.2.1` and check your code.

**Comment by gercog1** [comment]
@Norserium thanks, updating helps me 👍

**Comment by gercog1** [comment]
@Norserium May I somehow disable inertia scroll on mobile devices?

**Comment by Norserium** [comment]
@gercog1, currently no, because it use default mobile scroll. 

I can add prop `nativeMobileScroll`, that can be set as `false` to use my custom scroll (like on desktop), but you will lost in this case inertia, scrolling an outer area after scroll to the end of container and some other features.

Why do you need to disable inertia?

**Comment by gercog1** [comment]
It would be super cool if you add such property. I developed wheel component which can be used by user to select some values, and it should work without inertia
![Screen Shot 2019-08-14 at 15 51 57](https://user-images.githubusercontent.com/22454747/63022527-c973b800-beab-11e9-8bfb-394cfd354700.png)

**Comment by Norserium** [comment]
Could you install `1.1.3` and check the behavior of scroller?

**Comment by gercog1** [comment]
Using 1.1.3 I have issue with calling onEndScroll handler on every click everywhere on the page :(

**Comment by Norserium** [comment]
Yes, I know, but just test the scrolling behavior.

**Comment by gercog1** [comment]
Scrolling behavior is what I need!

**Comment by Norserium** [comment]
I understood you, I will think about the changes. Thanks.

**Comment by gercog1** [comment]
Thanks for quick response! :)

**Comment by Norserium** [comment]
You are welcome!

**Comment by Norserium** [comment]
@gercog1, check `1.3.0` version. I've added `nativeMobileScroll` prop.

**Comment by gercog1** [comment]
@Norserium thanks mate, you are best 🥇 :)
