### ISSUE TITLE
onScroll is not triggered with mouse wheel

### ISSUE THREAD

**Issue by smesgr** [Norserium/react-indiana-drag-scroll#15]
Hi,

thanks again for the great component. I have some issues to get onScroll work with mouse wheel.

```
<ScrollContainer className={modalContentClass}
                      horizontal={false}
                      vertical={true}
                      onScroll={this.handleScroll}>
                      {...}
</ScrollContainer>
```

This workaround works for me:
```
                <ScrollContainer className={modalContentClass}
                    horizontal={false}
                    vertical={true}
                    ref={(node: any) => {
                        if (node && node.container) {
                            // workaround container will not expose scroll with wheel
                            node.container.current.onscroll = this.handleScroll;
                        }
                    }}>
                    {this.getContent()}
                </ScrollContainer>
```

Testet on:
Firefox 69.0.2/Linux
Chromium 77.0.3865.90/Linux
with react 16.4.2 & react-indiana-drag-scroll 1.3.0

Thanks & Best Regards

**Comment by Norserium** [comment]
Hello again, @smesgr! 

Could you give the link to sandbox that illustrates your problem (you can use [this](https://codesandbox.io/s/react-example-816ln) as a template)? This library is not design to scroll by mouse wheel, so I can't imagine how you scroll it by one.

**Comment by smesgr** [comment]
Hi @Norserium,

thanks for looking into this. Indeed seems to be a leftover from the old app behaviour. I could simulate it:
https://codesandbox.io/s/react-example-20pfc

in our app the .container class style is after react-indiana-drag-scroll classes thus the !important  from the example above is not set. But the overflow state seems to enable the unintended feature.

Didn't noticed this because otherwise seems to work fine.

**Comment by Norserium** [comment]
I can add the special prop `wheelScroll` (default `false`), for example, if you need this behavior.

**Comment by smesgr** [comment]
thanks for your support. Could you please explain what the prop should do? If wheel scroll is not supported I will keep the hack or maybe add support in a merge request if i have time.

Best Regards

**Comment by Norserium** [comment]
Please look at this [sanbox](https://codesandbox.io/s/react-example-8l318). Is this result appropriate for you?

**Comment by smesgr** [comment]
wow thanks looks great.

**Comment by Norserium** [comment]
Update then to `1.4.2`

**Comment by Norserium** [comment]
Is your problem solved?

**Comment by Norserium** [comment]
I'm closing the issue now. Please reopen it if you encounter this problem in the future.

**Comment by smesgr** [comment]
I'm sorry was busy with other tasks. The 1.4.2 is integrated and tested and seems to work just fine. Thank you very much

**Comment by Norserium** [comment]
You are welcome!
