### ISSUE TITLE
Vertical scroll not working ?

### ISSUE THREAD

**Issue by donpernino** [Norserium/react-indiana-drag-scroll#16]
Hello,

I tried to use the plugin like so :

`<ScrollContainer className="scroll-container" vertical={true} horizontal={true}>
<MyImage />
</ScrollContainer>`

I am able to scroll horizontally by dragging but I can't move vertically at all. I don't know what I should do.

Thanks

**Comment by Norserium** [comment]
Hello! 

Could you upload the example, that illustrates your problem?

I can't reproduce this bug [here](https://codesandbox.io/s/react-example-ifg8z).

**Comment by donpernino** [comment]
Here you go : https://codesandbox.io/s/determined-meadow-et4xq?fontsize=14 :)

**Comment by Norserium** [comment]
There is no problem. Your image resizes container vertically, so it fits completely in the container.

Just set the max height of your container and scroll will be appear:
https://codesandbox.io/s/test-indiana-drag-scroll-e1xgm

**Comment by donpernino** [comment]
Okay my bad indeed, I did not think of the max-height. Sorry and thanks for the reactivity

**Comment by Norserium** [comment]
@donpernino, you are welcome!

**Comment by Norserium** [comment]
@Kamlesh-62, what's version do you use?

**Comment by Kamlesh-62** [comment]
i guess latest one @2.2.0

**Comment by Norserium** [comment]
@Kamlesh-62, try to use `@next` version for test.

**Comment by Kamlesh-62** [comment]
You means this version @3.0.3-alpha

**Comment by Kamlesh-62** [comment]
Nope, I tried with this @3.0.3-alpha, it is not scrolling, even the whole right part gets hidden. I you have any solution for the current version?

**Comment by Kamlesh-62** [comment]
Thanks find a solution. On the scroll-container "Div", I gave 100vh height it worked. I don't know why it did not work on the default height from the browser. Thanks, BTW.

**Comment by Norserium** [comment]
@Kamlesh-62, all's well that ends well.
