### ISSUE TITLE
Mobile stuttering

### ISSUE THREAD

**Issue by PabloSzx** [Norserium/react-indiana-drag-scroll#18]
Hey, I was having severe stuttering at the first attempt to drag scroll in mobile, so I just spent some time debugging and in the end I found a [partial solution](https://github.com/PabloSzx/react-indiana-drag-scroll/commit/ba5d062a79791b2b1e235dd8eabf27ccbb432cec), which only works with **activationDistance={1}**.

I am not sure if this is a common problem, and if this solution opens other problems for other implementations of this library (not my case), and this solution is kinda improvised, so I don't know if it's an immediate pull request worthy solution.

Here is this published version if needed https://www.npmjs.com/package/@pablosz/react-indiana-drag-scroll

**Comment by Norserium** [comment]
Hello, @PabloSzx! Could you send the video of your problem?

**Comment by Norserium** [comment]
Your solution looks like a blend of native mobile scrolling and non native mobile scrolling. It's pretty unpredictable.

**Comment by PabloSzx** [comment]
> Hello, @PabloSzx! Could you send the video of your problem and check if the bug appears at [this example](https://norserium.github.io/react-indiana-drag-scroll/)?

https://imgur.com/a/qSXjf48

Gifs recordings of the 4 options between fork - original , activation distance 1 vs 10 (any)

**Comment by Norserium** [comment]
I did some fixes and publish the example version with them. I will prepare the new release soon, that will include them.

**Comment by Norserium** [comment]
Please update to `1.5.0`

**Comment by PabloSzx** [comment]
It's fixed 😄 it's buttery smooth on mobile too, and works with any activation distance 🎉 

thank you very much

**Comment by Norserium** [comment]
Frankly, the activation distance is currently useless for native mobile scroll. It's predicted by browser himself.

**Comment by Norserium** [comment]
@PabloSzx, could you check example again? I've realized that I break one feature during the fixing that bug.

**Comment by PabloSzx** [comment]
> @PabloSzx, could you check the [example](https://norserium.github.io/react-indiana-drag-scroll/) again?
> 
> I've realized that I break one feature during the fixing that bug (there might be an undesirable click after the end of scroll at the desktop).

I don't catch it, it seems fine to me

**Comment by Norserium** [comment]
Thanks! Anyway, I will publish `1.5.1` that fixes that problem with click.
