### ISSUE TITLE
How can I change the scroll position using hooks?

### ISSUE THREAD

**Issue by donpernino** [Norserium/react-indiana-drag-scroll#19]
Hi,

I want to find a way to set the scroll position when clicking on a button (just an example).

I stumbled upon this [example](https://codesandbox.io/s/react-example-816ln) from Issue #4 but I can't think of doing the same thing within a react hook.

So far I can get the current scroll position by using `useRef` and `useEffect` but I don't know how to modify the scroll position.

Do you have any ideas on how I can possibly do that ?

**Comment by Norserium** [comment]
Hello! 

I don't see a problem right now. I've made the [example](https://codesandbox.io/s/react-example-r70i7). Is that you want to get?

**Comment by donpernino** [comment]
Yes perfect, it's what I wanted, your example is very clear, I didn't know how to pass the container to the `findDOMNode` on click.

Thanks a lot

**Comment by Norserium** [comment]
You are welcome!
