### ISSUE TITLE
IgnoreElements Doesn't work for generated class.

### ISSUE THREAD

**Issue by hridoy43** [Norserium/react-indiana-drag-scroll#22]
I have implemented a table (prime react) into ScrollContainer component. 

After implementing this. Scrolling works fine. but there is an issue. I wanted to ignore the table header, Which will not be scroll-able. 

So, actually prime react generate a class for table header . And i'v tried to pass this class in ignoreElemnts prop. But nothing hapen. Table header still is scroll-able.

**Sample Code:**
`<ScrollContainer ignoreElements=".p-datatable-header">
                                            <DataTable
                                                header={"Grade Configuration"}
                                                responsive={true}
                                                value={this.state.gradeConfigurationDataTable}
                                            >
                                                <Column field="amounta" header="A" body={tableDataValueWrapper} style={{ width: '220px' }} />
                                                <Column field="amountb" header="B" body={tableDataValueWrapper} style={{ width: '220px' }} />
                                                <Column field="amountc" header="C" body={tableDataValueWrapper} style={{ width: '220px' }} />
                                                <Column field="amountd" header="D" body={tableDataValueWrapper} style={{ width: '220px' }} />
                                                <Column field="amounte" header="E" body={tableDataValueWrapper} style={{ width: '220px' }} />
                                                <Column field="amountf" header="F" body={tableDataValueWrapper} style={{ width: '220px' }} />
                                                <Column field="amountg" header="G" body={tableDataValueWrapper} style={{ width: '220px' }} />
                                                <Column field="amounth" header="H" body={tableDataValueWrapper} style={{ width: '220px' }} />
                                                <Column field="amounti" header="I" body={tableDataValueWrapper} style={{ width: '220px' }} />
                                            </DataTable>
                                        </ScrollContainer>`

**Here's the generated code after rendering:**
`<div class="indiana-scroll-container indiana-scroll-container--hide-scrollbars"><div class="p-datatable p-component p-datatable-responsive"><div class="p-datatable-header">Grade Configuration</div><div class="p-datatable-wrapper"><table><thead class="p-datatable-thead"><tr><th class="" style="width: 220px;"><span class="p-column-title">A</span></th><th class="" style="width: 220px;"><span class="p-column-title">B</span></th><th class="" style="width: 220px;"><span class="p-column-title">C</span></th><th class="" style="width: 220px;"><span class="p-column-title">D</span></th><th class="" style="width: 220px;"><span class="p-column-title">E</span></th><th class="" style="width: 220px;"><span class="p-column-title">F</span></th><th class="" style="width: 220px;"><span class="p-column-title">G</span></th><th class="" style="width: 220px;"><span class="p-column-title">H</span></th><th class="" style="width: 220px;"><span class="p-column-title">I</span></th></tr></thead><tbody class="p-datatable-tbody"><tr class="p-datatable-row" style="height: 28px;"><td class="" style="width: 220px;"><span class="p-column-title">A</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">B</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">C</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">D</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">E</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">F</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">G</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">H</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">I</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td></tr><tr class="p-datatable-row" style="height: 28px;"><td class="" style="width: 220px;"><span class="p-column-title">A</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">B</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">C</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">D</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">E</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">F</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">G</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">H</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">I</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td></tr><tr class="p-datatable-row" style="height: 28px;"><td class="" style="width: 220px;"><span class="p-column-title">A</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">B</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">C</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">D</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">E</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">F</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">G</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">H</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">I</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td></tr><tr class="p-datatable-row" style="height: 28px;"><td class="" style="width: 220px;"><span class="p-column-title">A</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">B</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">C</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">D</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">E</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">F</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">G</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">H</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">I</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td></tr><tr class="p-datatable-row" style="height: 28px;"><td class="" style="width: 220px;"><span class="p-column-title">A</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">B</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">C</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">D</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">E</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">F</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">G</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">H</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td><td class="" style="width: 220px;"><span class="p-column-title">I</span><div class="admin-point"><div class="calculation-box-wrapper"><div class="calculation-box-inner-wrapper"><div class="calculation-box-field percentSign"><input name="fixedPercent" class="p-inputtext p-component" value="20"></div><div class="calculation-box-amount">00.00/-</div></div></div></div></td></tr></tbody></table></div></div></div>`

**Comment by Norserium** [comment]
Hello, @hridoy43!

Do you want to prevent scrolling of `Grade Configuration` string or the header with columns `A`, `B`, `C` and etc.?

In the second case you should pass to `ignoreElements` prop the following selector: `p-datatable-thead`.

**Comment by Norserium** [comment]
@hridoy43, did you solve your problem?

**Comment by hridoy43** [comment]
> Hello, @hridoy43!
> 
> Do you want to prevent scrolling of `Grade Configuration` string or the header with columns `A`, `B`, `C` and etc.?
> 
> In the second case you should pass to `ignoreElements` prop the following selector: `p-datatable-thead`.

I had tried in this way. But it did not work. However, I solved it in another way.
