### ISSUE TITLE
on mouse wheel

### ISSUE THREAD

**Issue by kewogc** [Norserium/react-indiana-drag-scroll#24]
is not taken effect onScroll on wheel my mouse ?

**Comment by Norserium** [comment]
Hello, @kewogc! I suppose, it's the bug. I will fix it later.

**Comment by Norserium** [comment]
@kewogc, this bug is fixed in `1.5.5`. Please update to the latest version.

**Comment by joserocha3** [comment]
Is there an option to not scroll on mouse wheel event? I can't find one.
