### ISSUE TITLE
`hideScrollbars` prevents horizontal scrolling

### ISSUE THREAD

**Issue by nemosmithasf** [Norserium/react-indiana-drag-scroll#26]
if `hideScrollbars` is true, then you can no longer scroll horizontally with a trackpad or wheel.

If so, it's probably worth leaving a note in documentation

As a side note, perhaps it's possible to consider implementing
```
  &::-webkit-scrollbar {
    display: none;
  }
```
instead?

**Comment by Norserium** [comment]
Hello, @nemosmithasf!

It's the good question. I'm not sure, what's the behavior should be for a wheel (a touchpad should work well, but I receive the reports, that sometime it doesn't).

You are able to scroll by wheel only vertically, so it can be perceived as an oddly behavior.

**Comment by nemosmithasf** [comment]
I've tried scrolling using the horizontal scroll wheel on an MX Master 2, and it didn't work.
I also tried using the MacBook Pro trackpad for horizontal scrolling, which also didn't work.

Interestingly, if I turn off `hideScrollBars`, then the horizontal functionality returns. I was also able to hide the bar using the `-webkit-scrollbar` styling detailed above

**Comment by sntk** [comment]
@nemosmithasf When you set `hideScrollBars` to true, the container must have `overflow: auto;`. If you inspect the element, you'll notice `indiana-scroll-container--hide-scrollbars` class is added with `overflow: hidden`.

Hope this helps! :)

**Comment by YLeventhal** [comment]
just adding to @sntk 's post, if you change the overflow:hidden => overflow: auto or scroll, you will have scroll ability and the scroll bars will still be hidden because of the styling you have placed on them. 
FYI a lot of those rules ie. 
-ms-overflow-style: none;
    scrollbar-width: none;
    &::-webkit-scrollbar

are not standard as per MDN and are advised against using.

Other than that, nice job.

**Comment by Norserium** [comment]
Hello, @YLeventhal!

> are not standard as per MDN and are advised against using.

Do you have any other idea how to hide scrollbars and preserve native mobile scroll?

**Comment by maxwellfortney** [comment]
Can confirm the overflow properties are conflicting and preventing the scroll with a wheel. By unchecking `overflow: hidden` the scroll function with the mouse wheel is returned.

![image](https://user-images.githubusercontent.com/29241388/114260293-e5da3780-99a1-11eb-9324-1d7e82b86035.png)

**Comment by Norserium** [comment]
@maxwellfortney do you want to preserve scroll by mouse wheel along with scroll by dragging?

**Comment by maxwellfortney** [comment]
@Norserium For my use case yes, I needed the mouse wheel as well as the mouse drag to work. Adding that css allows that. Ideally a toggle like `preventWheelScroll` would be nice.

Also this is a separate feature request, but I was trying to make it so the div would scroll horizontally without having to hold down shift. But I was unable to get this to work. Not critical, but a nice to have.

**Comment by Norserium** [comment]
@maxwellfortney, according to your code above you don't mind if scrollbars appears?

**Comment by maxwellfortney** [comment]
No, the scrollbars are still hidden with that CSS. The properties are just crossed out because they are added from CSS autoprefixer I assume, and are not being used on chrome.

**Comment by maxwellfortney** [comment]
To be honest, and I don't mean this in a rude way, but the performance of this package is awful compared to [react-scrollbooster](https://github.com/oberonamsterdam/react-scrollbooster#readme). Your package was very choppy for me when using the mouse drag, and was pretty much unusable when I needed to access the onScroll element, react-scrollbooster is quite smooth using both the transform, and native scroll methods.

**Comment by Norserium** [comment]
@maxwellfortney, it's okay. But personally I don't feel the perceptible difference (except that `scrollbooster` has inertia). Could you provide the examples to compare?

**Comment by maxwellfortney** [comment]
Unfortunately I scrapped the code using this package and didn't commit it, but it was about a 200x4 horizontal grid of emojis characters. I can try to make a comparison demo for you tomorrow.

**Comment by Norserium** [comment]
@maxwellfortney I would appreciate it. And, of course, there's no rush.

**Comment by Norserium** [comment]
@nemosmithasf, this issue is resolved in [`3.x.x`](https://norserium.github.io/react-indiana-drag-scroll/). Try it now:
```
npm install react-indiana-drag-scroll@next
```
