### ISSUE TITLE
Implementing `scroll-snap` css

### ISSUE THREAD

**Issue by nemosmithasf** [Norserium/react-indiana-drag-scroll#27]
It seems like it'll be pretty trivial to implement scroll snap, given its a low hanging fruit, perhaps its worth considering?

This is the code I used to get it to work (on parent contaienr):
```

const Container = styled.div`
  & .indiana-scroll-container {
    scroll-snap-type: x;

    &.indiana-scroll-container--dragging {
      scroll-snap-type: none !important;
    }
 }
```

The only problem I've encountered is that with mobile, scrolling also triggers `indiana-scroll-container--dragging`, which can probably be solved with media-queries; but perhaps there should be two decorators? i.e. `--dragging` and `--touchDragging`

**Comment by Norserium** [comment]
Hello, @nemosmithasf! 

I'm not sure, that `scroll-snap-type` will work well at the desktop devices. Me need much time to investigate how to implement this particular feature.

But, if I understood you correctly, you want to disable it on desktop devices, but enable on mobile devices?

In this case you can write this workaround:
```
const Container = styled.div`
    & .indiana-scroll-container--native-scroll {
      scroll-snap-type: scroll-snap-type: x;
    }
`
```

**Comment by Norserium** [comment]
@nemosmithasf, any news?

**Comment by nemosmithasf** [comment]
@Norserium Hey, sorry, didn't realize you were expecting a response.

It's been a while since I tried was working with this package, but if I remember correctly, the work-around worked for my purposes.
