### ISSUE TITLE
Make SCROLL_END_DEBOUNCE a prop

### ISSUE THREAD

**Issue by jportella93** [Norserium/react-indiana-drag-scroll#32]
Hey! this is such a nice component, I've been implementing it today. 

I don't really get why [SCROLL_END_DEBOUNCE](https://github.com/Norserium/react-indiana-drag-scroll/blob/master/src/index.js#L11) is a constant... changing it to be a prop which defaults to `300` would make it more flexible.. and is a two line change. 

Can you update it? If you want I can make a PR myself. I just don't want to fork out my own package to just change two lines 😄

**Comment by Norserium** [comment]
Hello, @jportella93! I'm ready to add `scrollEndDebounce` prop, but could you explain, why do you need to change the value of this parameter?

**Comment by jportella93** [comment]
I'm putting in sync two sibling scroll containers, where the parent holds the scroll position state of both. I've achieved it already by setting the minimal scroll distance to 0 (I think it defaults to 10) and debouncing to 0.

**Comment by Norserium** [comment]
But if you set debouncing to `0` scrolling by inertia on mobile devices will invoke `onStartScroll` and immediately `onEndScroll` numerous times instead of invoking `onScroll`:
![screenshot](https://user-images.githubusercontent.com/9862719/81099664-f07b8980-8f13-11ea-9085-ee63f03a4d7a.png)

**Comment by jportella93** [comment]
@Norserium Hmm that's right, I didn't notice because I'm building a desktop-only app :) What do you think It could be a solution for linking scroll between two ScrollContainer without delays?

**Comment by Norserium** [comment]
@jportella93, have you tried to use `onScroll` prop to synchronize the containers?

**Comment by jportella93** [comment]
@Norserium wow I was doing some weird stuff with `onStartScroll` and `onEndScroll` but turns out I really needed to use `onScroll` properly! thank you very much for your help :)

**Comment by Norserium** [comment]
@jportella93 you are welcome! I suppose, that I should postpone the introducing of the new prop `scrollEndDebounce`, because I don't see any case which requires it,

**Comment by jportella93** [comment]
@Norserium definitely. That was just a wrong use from my part!

**Comment by Norserium** [comment]
I close the issue then. If someone encounter the necessity to change this property feel free to tell to reopen this issue.
