### ISSUE TITLE
Supress element.scrollTo(...) events

### ISSUE THREAD

**Issue by FBNitro** [Norserium/react-indiana-drag-scroll#38]
Looking at the README:

onScroll | Function | Invoked when user scrolling container |  
onEndScroll | Function | Invoked when user ends scrolling container |  
onStartScroll | Function | Invoked when user starts scrolling container |

But when I set the initial scroll using the domNode.scrollTo(...); the start/end scroll callbacks are invoked.

Is there any way we can supress this easily? 

I've attempted to do this within my app with isInitialized flags etc, but it's quite unreliable.  I believe since you know if the user touched/moused etc, this may be easier to handle in the component.

Thanks.

**Comment by Norserium** [comment]
@FBNitro the experimental feature that allows to distinguish appeared in `2.0.0`:
```js
onScroll(event) {
    if (event.external) {
       console.log('This events comes outside the scroll container').
    } else {
       console.log('This event produces by user interaction with the scroll container')
    }
}
```
