### ISSUE TITLE
Scrolling with mouse's scroll and set element type

### ISSUE THREAD

**Issue by jhenriquevissotto** [Norserium/react-indiana-drag-scroll#39]
Nice library brow!! Thanks very much!

But you could add more two new features:

1) Horizontal scrolling with mouse's scroll.

And (2) set element type in component. Example:

```
<DraggableScroll element="ul" >
    {list.map(({ name }, i) => (
        <li key={i} >{name}</li>
    ))}
</DraggableScroll>
```

**Comment by Norserium** [comment]
Hello, @jhenriquevissotto! I don't understand, what the first feature means? The second feature looks reasonable.

**Comment by Norserium** [comment]
@jhenriquevissotto, the second feature is implemented in `0.17.0`. I've added `component` property`.

**Comment by Blackoutseeker** [comment]
@jhenriquevissotto You can press and hold SHIFT (left) key and scroll the mouse.

**Comment by Norserium** [comment]
Closed due inactivity.
