### ISSUE TITLE
Scroll disables zooming on Android Chrome browser

### ISSUE THREAD

**Issue by Somoth** [Norserium/react-indiana-drag-scroll#42]
Hi, great library and everything works fine in Safari and Chrome on the Iphone, but when I open webpage on Android (using Chrome) I cannot zoom this page, like sometimes I can, but most of the times no. I've commented ScrollContainer and everything works just fine, maybe someone else met that issue, I haven't found anything which can cause it.

**Comment by Norserium** [comment]
Hello, @Somoth! Could you provide a codesanbox that reproduces your error? Do you encounter this bug on example pages?

**Comment by Norserium** [comment]
@Somoth, any news?

**Comment by Norserium** [comment]
@Somoth, I close issue. Feel free to reopen if you encounter this issue again.
