### ISSUE TITLE
Horizontal demo

### ISSUE THREAD

**Issue by headwinds** [Norserium/react-indiana-drag-scroll#43]
I have no issue but just wanted express my gratitude to you from creating this library

I had a design that required both drag and scrollbars, and was able to [prototype it](https://codesandbox.io/s/react-indiana-drag-scrolls-e4jby?file=/index.js) with react-indiana-drag-scroll - this has saved me considerable amount of time

thank you!

**Comment by Norserium** [comment]
You are welcome!
