### ISSUE TITLE
TypeScript errors

### ISSUE THREAD

**Issue by davmey** [Norserium/react-indiana-drag-scroll#47]
Installed with Yarn, imported into a .tsx file and after using the ScrollContainer in my JSX got this error:

`JSX element class does not support attributes because it does not have a 'props' property.  TS2607`

**Comment by Norserium** [comment]
@davmey are you sure, that you've configured TypeScript correctly? There is [the codesanbox](https://codesandbox.io/s/react-indiana-drag-scroll-typescript-initial-scroll-innerref-9qft5?file=/src/index.tsx).

**Comment by Norserium** [comment]
@alvinchoi028 I close issue. Feel free to ask, if you encounter this problem in the future.
