### ISSUE TITLE
Drag Inertia

### ISSUE THREAD

**Issue by tomswork** [Norserium/react-indiana-drag-scroll#5]
Hey guys - is it possible to include some level of animated inertia to the drag? Also any possibility of including scroll capture in the element as well?

**Comment by Norserium** [comment]
Hello! 

Could you provide the example of what you want to get? 

And what do you mean by the _scroll capture_? There is `onScroll`, `onStartScroll` and `onEndScroll` callbacks.

**Comment by Norserium** [comment]
@tomswork, is this problem still actual? Did you achieve the needed result?

**Comment by tomswork** [comment]
@Norserium Sorry its taken me a while to get back to you - Scroll capture as in - on user scroll the container scrolls the content left and right. I ended up going with another solution which didnt require a drag. With the inertia - a good example is the inertia from a drag down a webpage with a touch device.

**Comment by ifitzsimmons** [comment]
Hello All,

Love the package. Did anyone ever add drag inertia to it? Would be an awesome feature.

By drag inertia I mean the ability to swipe  and have the container continue to scroll for some time depending on the speed of the swipe

**Comment by nightmareinc** [comment]
Hey guys,

I need a similar feature in my current project. my goal is to have the drag animated like in this website https://www.erikasenftmiller.com/ 

can anybody guide me?

**Comment by Norserium** [comment]
@nightmareinc, I suppose, that architecture of this library should be different to implement the drag inertia correctly. This library is intentionally made as simple as it could be.

So I'm really not sure, that I will implement this feature in the near future. You can you the source of this library to implement your own component or use an alternative (for example, [ScrollBooster](https://github.com/ilyashubin/scrollbooster) or its [react wrapper](https://github.com/oberonamsterdam/react-scrollbooster)).

**Comment by nightmareinc** [comment]
@Norserium thank you this was very helpful.

**Comment by Norserium** [comment]
@tomswork, @nightmareinc , @ifitzsimmons, this feature is added in [the next major version (currently in the alpha test)](https://norserium.github.io/react-indiana-drag-scroll/).
