### ISSUE TITLE
Feature Request: export the current scroll offset

### ISSUE THREAD

**Issue by tlawork** [Norserium/react-indiana-drag-scroll#50]
I am using react-indiana-drag-scroll to drop a pin on an image. The pin is stationary on top and the image is scrolled underneath just like the indiana-jones and hieroglyph example.  The only thing is in order to know the pin location, once scrolling stops I need to figure out how much scrolling in x and y was made.

Is there a way right now to get that value from the component?

If not is there a way the current scroll value could be added as an output?

thank you.

**Comment by Norserium** [comment]
Hello, @tlawork! Check [this example](https://codesandbox.io/s/react-indiana-drag-scroll-default-forked-qi5e6?file=/index.js).

**Comment by tlawork** [comment]
thanks for the update. closing issue

**Comment by Norserium** [comment]
@tlawork, actually, I didn't update anything, I just built the example. Anyway, you are welcome!

**Comment by tlawork** [comment]
Hey - I figured your example was solution enough and you don't need to add anything else.  However if you think there is code you could add to make it easier or any other related improvement, feel free to reopen - for my part you helped a lot.  thanks again.
