### ISSUE TITLE
[Request] Be able to change cursor

### ISSUE THREAD

**Issue by marnix-warp** [Norserium/react-indiana-drag-scroll#55]
I would like to be able to change the cursor from 'grab' to 'grabbing',

So I can use cursor 'grab' on hover and cursor 'grabbing' when mouse is down.

Currently the class indiana-dragging is setting the cursor with !important so I cannot overrule this functionality

**Comment by Norserium** [comment]
@marnix-warp, what's version do you use?

**Comment by marnix-warp** [comment]
@Norserium Version 2.0.0

**Comment by Norserium** [comment]
@marnix-warp fixed in `2.0.1`.

**Comment by Norserium** [comment]
@marnix-warp, I close the issue. If you encounter any troubles, feel free to reopen.
