### ISSUE TITLE
Testing issues

### ISSUE THREAD

**Issue by 0mickel0** [Norserium/react-indiana-drag-scroll#56]
Hello
I can't write a test on a component with imported ScrollContainer. I'm using a @testing-library/react for tests.

Faced with the following problem:
`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

I think the problem is in the named import `import ScrollContainer from 'react-indiana-drag-scroll';` but I didn't find any other ways to import it

I would be grateful for an example of testing components with 'react-indiana-drag-scroll' or any other helpful ideas

**Comment by Norserium** [comment]
Hello, @0mickel0! What's the library version do you use? Do you use CRA?

**Comment by 0mickel0** [comment]
@Norserium ,Thanks for attention 

Unfortunately does not work in my environment
I'm using
"react": "16.14.0",
"@testing-library/react": "11.0.2",

```js
import * as React from 'react';

import { render, screen } from '@testing-library/react';
import ScrollContainer from 'react-indiana-drag-scroll';

import TestingComponent from './TestingComponent';

it('renders scroll container', () => {
  render(<ScrollContainer />);
  screen.debug();
});

it('renders TestingComponent', () => {
  render(<TestingComponent />);
  screen.debug();
});

```

For 
```js
import * as React from 'react';

import ScrollContainer from 'react-indiana-drag-scroll';

const TestingComponent: React.FC = () => (
    <ScrollContainer>
      <h1>1</h1>
      <h1>2</h1>
      <h1>3</h1>
      <h1>4</h1>
    </ScrollContainer>
  );

export default TestingComponent;
```

Both tests failed with the same error (text in description)
![image](https://user-images.githubusercontent.com/32054482/115677607-50ec1c80-a359-11eb-81b3-bc195daeb5e8.png)

**Comment by Norserium** [comment]
Do you use Create React App? What's version of `react-indiana-drag-scroll` do you use?

**Comment by 0mickel0** [comment]
@Norserium, I use custom build of react app.
I tried to repeat it in [codesandbox](https://codesandbox.io/s/react-indiana-drag-scrolltesting-testing-7wqhm?file=/src/index.spec.tsx) and everything works without any problems. So I will close the discussion because the issue is not related to the library. 
I will look for a problem in my project. Thanks for your time and for the library!

**Comment by Norserium** [comment]
@0mickel0, anyway, what's version of `react-indiana-drag-scroll` do you use?

**Comment by Norserium** [comment]
@0mickel0, perhaps, something wrong with your jest config or typescript config. For example, incorrect `module` value in the last one.
