### ISSUE TITLE
No way to get scroll offsets

### ISSUE THREAD

**Issue by kosachevds** [Norserium/react-indiana-drag-scroll#58]
In version [2.0.0](https://github.com/Norserium/react-indiana-drag-scroll/releases/tag/v2.0.0) (and later) the parameters of the `onEndScroll` function have been replaced with `ScrollEvent`, which contains a single `external` field. So the opportunity to get scrolling offsets was lost.

**Comment by Norserium** [comment]
@kosachevds, no, it's not. You can get the ref to the root and get offset from it:
```js
  const container = useRef(null);
  const onScroll = () => {
       if (container.current) {
           console.log(container.current.scrollTop, container.current.scrollLeft)
       }
  }
```

**Comment by kosachevds** [comment]
OK, thanks

**Comment by Norserium** [comment]
You are welcome!
