### ISSUE TITLE
Any plan to support React 18?

### ISSUE THREAD

**Issue by indrasantosa** [Norserium/react-indiana-drag-scroll#66]
As described on the title itself. Is there any plans to support React 18?

**Comment by Norserium** [comment]
@indrasantosa, try to update to `2.2.0`.

**Comment by indrasantosa** [comment]
I saw that, thanks @Norserium !

**Comment by black** [comment]
Did you guy make it work? I am using react 18.2.0 and it seems this isn't working. Have you guys found any work around?

**Comment by Norserium** [comment]
@black, it should work. What's kind of troubles do you have?
