### ISSUE TITLE
Activate drag scroll with the mouse wheel?

### ISSUE THREAD

**Issue by adrianhm13** [Norserium/react-indiana-drag-scroll#67]
Hello, 

Thanks for the library, it's quite cool! 

I'd like to add the wheel of the mouse to activate the drag and I've seen in your docs that you have the property buttons which receives an array to activate the drag scroll. The thing is that I don't really know which number belongs to the wheel or probably I'm getting wrong the button's property, if so. Is there a way to activate it with your API? 

Thanks again and have a wonderful day!

**Comment by Norserium** [comment]
@adrianhm13, i.e. you want to get something [like this](https://codesandbox.io/s/react-indiana-drag-scroll-middle-button-73etb2?file=/index.js)?

**Comment by adrianhm13** [comment]
That's it! thanks a lot @Norserium 

Have a great week!
