### ISSUE TITLE
Error throws specific environment

### ISSUE THREAD

**Issue by namevalues** [Norserium/react-indiana-drag-scroll#7]
Hi, I am student developer.
I'm using NextJS now, and make long div and it is only scrolling horizontally.
I works well, but chrome throw error below.

Unable to preventDefault inside passive event listener due to target being treated as passive.

How can i fix this error?

I dont use event listener without this library..
It is because of Nextjs?

**Comment by Norserium** [comment]
Hello! Could you provide the context, where is `ScrollContainer` placed?

**Comment by Norserium** [comment]
Hello! It's not an error, it's a warning. But anyway I fixed it `1.2.1`.

**Comment by namevalues** [comment]
@Norserium Yes. Thank you for your help :)
I'd like to contribute your library soon 👍

**Comment by Norserium** [comment]
You are welcome! I'd be happy to see your contribution.
