### ISSUE TITLE
Horizontal scroll not working with touchpad

### ISSUE THREAD

**Issue by jackherizsmith** [Norserium/react-indiana-drag-scroll#73]
On render, the scroll container isn't scrolling when using the touchpad (on MacOS). Fine on mobile with touch, and grabbing to scroll with mouse drag. This must be a known issue, with perhaps a simple fix? Thanks

**Comment by Norserium** [comment]
@jackherizsmith, which version do you use?

**Comment by jackherizsmith** [comment]
Hey sorry for delay coming back to you. I fixed it, sort of - I style the `ScrollContainer` using styled-components, and had restyled it i.e. 

```
const Scroll = styled(ScrollContainer)`
  overflow-x: scroll;
`;
```

But this was temperamental. Just found that inline styling worked, i.e. 

```
  <Scroll style={{overflowX: 'scroll'}}>
    // ....
  </Scroll>
```

so it must be to do with specificity; therefore, my solution was

```
const Scroll = styled(ScrollContainer)`
  overflow-x: scroll !important;
`;
```

Would be interested to know if there is an alternative way to do this properly.

**Comment by Norserium** [comment]
@jackherizsmith, could you answer on my previous questions? I need to figure out what's the nature of this bug.

**Comment by Norserium** [comment]
> `^2.2.0`

Could you try `3.0.0-alpha`?

**Comment by jackherizsmith** [comment]
that does seem to have worked yes 👍

**Comment by Norserium** [comment]
@jackherizsmith, thank you! I close the issue then.
