### ISSUE TITLE
'ScrollContainer' cannot be used as a JSX component.

### ISSUE THREAD

**Issue by alvaro-escalante** [Norserium/react-indiana-drag-scroll#74]
I the`ScrollContainer`  component fails with 

```
Its instance type 'ScrollContainer' is not a valid JSX element.
The types returned by 'render()' are incompatible between these types.
Type 'React.ReactNode' is not assignable to type 'import("../node_modules/@types/styled-components/node_modules/@types/react/index").ReactNode'.
Type '{}' is not assignable to type 'ReactNode'.
```

I have a simple implementation 

```
import React from 'react'
import ScrollContainer from 'react-indiana-drag-scroll'

export const Foo = () => {
    return (
      <ScrollContainer
         className='scroll-container'
         horizontal={true}
         vertical={true}
      >
        <h1>Test</h1>
    </ScrollContainer>
   )
})
```

**Comment by Norserium** [comment]
@alvaro-escalante, did you solve the issue?

**Comment by alvaro-escalante** [comment]
Yes, I had to implement these resolutions on package.json https://stackoverflow.com/questions/71791347/npm-package-cannot-be-used-as-a-jsx-component-type-errors

**Comment by Norserium** [comment]
@alvaro-escalante, thanks for the info. It could be helpful for other fellows.

**Comment by MatiSera** [comment]
Hi! I'm still having this issue. Do you know if there's anything else I can do?
I try the solution of adding the "resolutions" objects

**Comment by Norserium** [comment]
@MatiSera, what's version of `react` and `react-indiana-drag-scroll` do you use?

**Comment by MatiSera** [comment]
@Norserium `"react": "18.2"` "react-indiana-drag-scroll" :"^2.2.0"

I solved the issue, declaring the module on a declaration.d.ts file
