### ISSUE TITLE
Dragging problem on touch devices

### ISSUE THREAD

**Issue by cojoclaudiu** [Norserium/react-indiana-drag-scroll#76]
Hello, I have this issue which I recreated here:
https://codesandbox.io/s/eloquent-bouman-te4jj9?file=/src/App.js
https://te4jj9.csb.app/

The issue is on touch devices when I try to scroll vertically from the <ScrollableContainer>

**Comment by Norserium** [comment]
@cojoclaudiu, could you record the video of the issue? 

If you use the mobile devices it should use native scroll instead of the custom one.

Also, what's the library version do you use?

**Comment by cojoclaudiu** [comment]
thank you for reply @Norserium 

https://user-images.githubusercontent.com/62800983/212533769-943d1a00-151a-49bf-926b-98654c880d78.mov

The main pages has a overflow-y but you can't drag up because of the <ScrollContainer> which has a overflow-x, you can drag up if you drag outside the ScrollContainer. Sorry for the confusion but I mixed drag up/down with scroll.

The mouse scroll it's working but not the drag on the tocuh devices.
I'm using version 2.2.0

**Comment by Norserium** [comment]
@cojoclaudiu, I see. 

Try to use `@next` version and reproduce this error.

**Comment by cojoclaudiu** [comment]
> @cojoclaudiu, I see.
> 
> Try to use `@next` version and reproduce this error.

It's exactly the same issue

**Comment by cojoclaudiu** [comment]
@Norserium with `@next` the scrollbars are not hidden and I need to add overflow-x auto to make it work

**Comment by Norserium** [comment]
@cojoclaudiu, it's described in [the migration guide](https://norserium.github.io/react-indiana-drag-scroll/docs/migration). You should import the styles now explicitly:
```
import 'react-indiana-drag-scroll/dist/style.css'
```

**Comment by cojoclaudiu** [comment]
@Norserium thank you, I didn't know about new docs page. It's working now, thank you for help.

**Comment by Norserium** [comment]
@cojoclaudiu, you are welcome! Yeah, it was created relatively recently.
