### ISSUE TITLE
Anchor and img tags act weird as children in Firefox

### ISSUE THREAD

**Issue by Abisar** [Norserium/react-indiana-drag-scroll#8]
If the children are `a` or `img` tags in Firefox, they literally get dragged over the browser. It's a bit hard to explain, open this with Firefox: [https://gluye.csb.app/](https://gluye.csb.app) ([editor view](https://codesandbox.io/s/cool-sky-gluye?fontsize=14)).

**Comment by Norserium** [comment]
Hello! Could you update to `1.1.3` and check it?

**Comment by Abisar** [comment]
Awesome! Thanks it's solved.
