### ISSUE TITLE
scrollLeft not set when scrolling with mousewheel

### ISSUE THREAD

**Issue by Moorst** [Norserium/react-indiana-drag-scroll#80]
it's only available when dragging via the onScroll

```
const onScroll = () => {
    if (scrollContainerRef.current) {
      console.log(scrollContainerRef.current);
    }
};
```

I need the offset regardless of how the window is scrolled, is this possible?

**Comment by Norserium** [comment]
@Moorst, I didn't understand the issue. Could you illustrate the issue by the sandbox, for example?

**Comment by Moorst** [comment]
Apologies, this was happening in an older version but fine on the latest

**Comment by Norserium** [comment]
@Moorst, it's okay. I close the issue then.
