### ISSUE TITLE
Doesn't work with Next.js 13+

### ISSUE THREAD

**Issue by corysimmons** [Norserium/react-indiana-drag-scroll#86]
1. Start fresh Next.js project
2. Follow getting started docs here https://norserium.github.io/react-indiana-drag-scroll/
3. Shows the hand but doesn't actually drag

```tsx
// app/page.tsx on a fresh project
"use client";
import { ScrollContainer } from "react-indiana-drag-scroll";
import "react-indiana-drag-scroll/dist/style.css";

function Block({ children }: { children: React.ReactNode }) {
  return (
    <div style={{ width: 300, height: 300, backgroundColor: "red" }}>
      {children}
    </div>
  );
}

export default function Page() {
  return (
    <ScrollContainer>
      <Block>1</Block>
      <Block>2</Block>
      <Block>3</Block>
      <Block>4</Block>
      <Block>5</Block>
      <Block>6</Block>
      <Block>7</Block>
      <Block>8</Block>
      <Block>9</Block>
      <Block>10</Block>
    </ScrollContainer>
  );
}
```

I'm guessing this is Next.js 13. I'm on 14, but 13 is where they introduced the new router which probably broke a bunch of libs.

**Comment by corysimmons** [comment]
Posterity: https://gist.github.com/corysimmons/d85d6a6edadab1f0405b16640d2e8827

**Comment by Norserium** [comment]
@corysimmons, it works with Next, I've checked it. 

Just limit the height of the scroll container and it will be become scrollable, otherwise there is nothing to scroll and you will scroll the body of the document.

**Comment by corysimmons** [comment]
Oh you have to wrap `<ScrollContainer>` with a div with fixed dimensions?

```tsx
<div style={{ height: 500 }}>
  <ScrollContainer>
    <Block>1</Block>
  </ScrollContainer>
</div>
```

**Comment by Norserium** [comment]
@corysimmons, I've set height to `ScrollContainer`.
